title = "Infuse"
baseURL = "https://infuse.quest"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

rssLimit  = 300

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

pluralizeListTitles = false

[permalinks]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
    [markup.tableOfContents]
      startLevel = 2
      endLevel = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  # Metadata mostly used in document's head
  description = "Infuse is a community-developed framework helping digital protectors advance their knowledge and skill sets in areas of specialized technical expertise (STE)"
  keywords = "NGO, cybersecurity, digital security, malware, phishing, web security, OWASP"
  images = ["media/images/thumbnail.png"]

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/OpenInternet/Infuse/commit/"

  githubRepo = "https://github.com/OpenInternet/Infuse"
  githubBranch = "main"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Colors for favicons
  [params.favicon.color]
    mask = "#194E80"
    msapplication = "#194E80"

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"
  
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/products/x/"

[languages]
  [languages.en]
  languageName = "English"
  weight    = 1
  [languages.en.params]
    languageName = "English"
    direction = "ltr"

  [languages.fr]
  languageName = "French"
  weight    = 2
  [languages.fr.params]
    languageName = "French"
    direction = "ltr"

  [languages.es]
  languageName = "Spanish"
  weight    = 3
  [languages.es.params]
    languageName = "Spanish"
    direction = "ltr"
  
  [languages.ar]
  languageName = "Arabic (coming soon)"
  weight    = 4
  [languages.ar.params]
    languageName = "Arabic (coming soon)"
    direction = "rtl"

[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
